=== arkroger/acc-training/acc-json-tools/flat_laps_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ACCFlatLapArray",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "lap": {
        "type": "integer"
      },
      "time": {
        "type": "object",
        "properties": {
          "time": {
            "type": "integer",
            "description": "lap total in ms"
          },
          "formattedTime": {
            "type": "string"
          }
        },
        "required": [
          "time"
        ]
      },
      "splits": {
        "type": "array",
        "items": {
          "type": "integer"
        },
        "minItems": 3,
        "maxItems": 3
      },
      "formattedSplits": {
        "type": "array",
        "items": {
          "type": "string"
        },
        "minItems": 3,
        "maxItems": 3
      },
      "type": {
        "type": "string",
        "enum": [
          "Regular",
          "Outlap",
          "Inlap"
        ]
      },
      "valid": {
        "type": "boolean"
      },
      "boxLap": {
        "type": "boolean"
      },
      "clock": {
        "type": "string"
      },
      "position": {
        "type": "number"
      },
      "trackGripStatus": {
        "type": "string"
      },
      "tyre": {
        "type": "object",
        "properties": {
          "pressure": {
            "type": "object",
            "properties": {
              "frontLeft": {
                "type": "number"
              },
              "frontRight": {
                "type": "number"
              },
              "rearLeft": {
                "type": "number"
              },
              "rearRight": {
                "type": "number"
              }
            }
          },
          "temperature": {
            "type": "object",
            "properties": {
              "frontLeft": {
                "type": "number"
              },
              "frontRight": {
                "type": "number"
              },
              "rearLeft": {
                "type": "number"
              },
              "rearRight": {
                "type": "number"
              }
            }
          },
          "compound": {
            "type": "string"
          },
          "currentTyreSet": {
            "type": "integer"
          }
        }
      },
      "environment": {
        "type": "object",
        "properties": {
          "airTemperature": {
            "type": "number"
          },
          "roadTemperature": {
            "type": "number"
          },
          "rainIntensity": {
            "type": "string"
          },
          "windSpeed": {
            "type": "number"
          },
          "windDirection": {
            "type": "number"
          },
          "rainIntensityIn10min": {
            "type": "string"
          },
          "rainIntensityIn30min": {
            "type": "string"
          }
        }
      },
      "carInfo": {
        "type": "object",
        "properties": {
          "damage": {
            "type": "object"
          },
          "fuel": {
            "type": "number"
          },
          "fuelRealUsed": {
            "type": "number"
          },
          "fuelXLap": {
            "type": "number"
          },
          "usedFuel": {
            "type": "number"
          },
          "fuelEstimatedLaps": {
            "type": "number"
          },
          "tc": {
            "type": "number"
          },
          "tcCut": {
            "type": "number"
          },
          "abs": {
            "type": "number"
          }
        }
      }
    },
    "required": [
      "lap",
      "time",
      "valid"
    ]
  }
}

=== arkroger/acc-training/acc-json-tools/sample_flat_input.json
[
  {
    "lap": 1,
    "time": {
      "time": 90457,
      "formattedTime": "1:30.457"
    },
    "splits": [
      30842,
      29842,
      29772
    ],
    "formattedSplits": [
      "0:30.842",
      "0:29.842",
      "0:29.772"
    ],
    "type": "Regular",
    "valid": false,
    "boxLap": false,
    "clock": "21:02",
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "currentTyreSet": 1
    },
    "carInfo": {
      "fuel": 48.79
    }
  },
  {
    "lap": 2,
    "time": {
      "time": 89490,
      "formattedTime": "1:29.490"
    },
    "splits": [
      30287,
      29532,
      29670
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "21:04",
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "currentTyreSet": 1
    },
    "carInfo": {
      "fuel": 46.09
    }
  }
]

=== arkroger/acc-training/events/piloteiro-amador/2025-10-19_barcelona_60min/sessions/session10_adversario-silver_1.json
[
  {
    "lap": 1,
    "time": {
      "time": 106717,
      "formattedTime": "1:46.717"
    },
    "splits": [
      29690,
      41522,
      35505
    ],
    "formattedSplits": [
      "0:29.690",
      "0:41.522",
      "0:35.505"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:13",
    "position": 5,
    "tyre": {},
    "environment": {
      "airTemperature": 18,
      "roadTemperature": 18,
      "rainIntensity": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "-"
      }
    }
  },
  {
    "lap": 2,
    "time": {
      "time": 105782,
      "formattedTime": "1:45.782"
    },
    "splits": [
      29720,
      41067,
      34995
    ],
    "formattedSplits": [
      "0:29.720",
      "0:41.067",
      "0:34.995"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:15",
    "position": 4,
    "tyre": {},
    "environment": {
      "airTemperature": 18,
      "roadTemperature": 18,
      "rainIntensity": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "-"
      }
    }
  },
  {
    "lap": 3,
    "time": {
      "time": 112032,
      "formattedTime": "1:52.032"
    },
    "splits": [
      29560,
      40685,
      41787
    ],
    "formattedSplits": [
      "0:29.560",
      "0:40.685",
      "0:41.787"
    ],
    "type": "Inlap",
    "valid": false,
    "boxLap": true,
    "clock": "23:17",
    "position": 3,
    "tyre": {},
    "environment": {
      "airTemperature": 18,
      "roadTemperature": 18,
      "rainIntensity": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "-"
      }
    }
  }
]

=== arkroger/acc-training/events/2025/2025-10-19_barcelona_60min/data/session10_1.json
[
  {
    "lap": 1,
    "time": {
      "time": 106115,
      "formattedTime": "1:46.115"
    },
    "splits": [
      29885,
      40735,
      35495
    ],
    "formattedSplits": [
      "0:29.885",
      "0:40.735",
      "0:35.495"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:07",
    "position": 3,
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "pressure": {
        "frontLeft": 26.73711585998535,
        "frontRight": 26.6793212890625,
        "rearLeft": 26.57192611694336,
        "rearRight": 26.485034942626953
      },
      "temperature": {
        "frontLeft": 85.01033020019531,
        "frontRight": 70.86665344238281,
        "rearLeft": 89.53960418701172,
        "rearRight": 78.21783447265625
      },
      "compound": "DRY",
      "currentTyreSet": 1
    },
    "environment": {
      "airTemperature": 18.624475479125977,
      "roadTemperature": 18.624475479125977,
      "rainIntensity": "NO RAIN",
      "windSpeed": 3.0310754776000977,
      "windDirection": 110.05845642089844,
      "rainIntensityIn10min": "NO RAIN",
      "rainIntensityIn30min": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 55.67335510253906,
      "fuelRealUsed": 2.7699999809265137,
      "fuelXLap": 2.7699999809265137,
      "usedFuel": 4.32635498046875,
      "fuelEstimatedLaps": 20.09878921508789,
      "tc": 3,
      "tcCut": 0,
      "abs": 3
    }
  },
  {
    "lap": 2,
    "time": {
      "time": 105862,
      "formattedTime": "1:45.862"
    },
    "splits": [
      29907,
      40507,
      35447
    ],
    "formattedSplits": [
      "0:29.907",
      "0:40.507",
      "0:35.447"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:09",
    "position": 2,
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "pressure": {
        "frontLeft": 26.792987823486328,
        "frontRight": 26.67798614501953,
        "rearLeft": 26.7659969329834,
        "rearRight": 26.6109676361084
      },
      "temperature": {
        "frontLeft": 85.613525390625,
        "frontRight": 70.8739242553711,
        "rearLeft": 91.58236694335938,
        "rearRight": 79.5508041381836
      },
      "compound": "DRY",
      "currentTyreSet": 1
    },
    "environment": {
      "airTemperature": 18.592708587646484,
      "roadTemperature": 18.592708587646484,
      "rainIntensity": "NO RAIN",
      "windSpeed": 3.0340793132781982,
      "windDirection": 109.93250274658203,
      "rainIntensityIn10min": "NO RAIN",
      "rainIntensityIn30min": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 52.550045013427734,
      "fuelRealUsed": 3.123310089111328,
      "fuelXLap": 2.7283592224121094,
      "usedFuel": 7.449954986572266,
      "fuelEstimatedLaps": 19.260677337646484,
      "tc": 3,
      "tcCut": 0,
      "abs": 3
    }
  },
  {
    "lap": 3,
    "time": {
      "time": 105385,
      "formattedTime": "1:45.385"
    },
    "splits": [
      29665,
      40485,
      35235
    ],
    "formattedSplits": [
      "0:29.665",
      "0:40.485",
      "0:35.235"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:14",
    "position": 2,
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "pressure": {
        "frontLeft": 26.713516235351562,
        "frontRight": 26.784208297729492,
        "rearLeft": 26.643924713134766,
        "rearRight": 26.710969924926758
      },
      "temperature": {
        "frontLeft": 84.75884246826172,
        "frontRight": 70.9118881225586,
        "rearLeft": 89.24226379394531,
        "rearRight": 78.48234558105469
      },
      "compound": "DRY",
      "currentTyreSet": 1
    },
    "environment": {
      "airTemperature": 18.512712478637695,
      "roadTemperature": 18.512712478637695,
      "rainIntensity": "NO RAIN",
      "windSpeed": 3.0410873889923096,
      "windDirection": 109.6386489868164,
      "rainIntensityIn10min": "NO RAIN",
      "rainIntensityIn30min": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 45.515472412109375,
      "fuelRealUsed": 7.034572601318359,
      "fuelXLap": 2.729398727416992,
      "usedFuel": 4.484340667724609,
      "fuelEstimatedLaps": 16.676074981689453,
      "tc": 3,
      "tcCut": 0,
      "abs": 3
    }
  },
  {
    "lap": 4,
    "time": {
      "time": 105217,
      "formattedTime": "1:45.217"
    },
    "splits": [
      29787,
      40337,
      35092
    ],
    "formattedSplits": [
      "0:29.787",
      "0:40.337",
      "0:35.092"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "23:16",
    "position": 1,
    "trackGripStatus": "OPTIMUM",
    "tyre": {
      "pressure": {
        "frontLeft": 26.81113052368164,
        "frontRight": 26.860382080078125,
        "rearLeft": 26.863235473632812,
        "rearRight": 26.875038146972656
      },
      "temperature": {
        "frontLeft": 85.79717254638672,
        "frontRight": 71.72687530517578,
        "rearLeft": 91.54824829101562,
        "rearRight": 80.21287536621094
      },
      "compound": "DRY",
      "currentTyreSet": 1
    },
    "environment": {
      "airTemperature": 18.48046112060547,
      "roadTemperature": 18.48046112060547,
      "rainIntensity": "NO RAIN",
      "windSpeed": 3.0436902046203613,
      "windDirection": 109.52951049804688,
      "rainIntensityIn10min": "NO RAIN",
      "rainIntensityIn30min": "NO RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 42.3970832824707,
      "fuelRealUsed": 3.118389129638672,
      "fuelXLap": 2.7444393634796143,
      "usedFuel": 7.602851867675781,
      "fuelEstimatedLaps": 15.448382377624512,
      "tc": 3,
      "tcCut": 0,
      "abs": 3
    }
  }
]

=== arkroger/acc-training/events/piloteiro-amador/2025-10-19_barcelona_60min/sessions/session8_3.json
[
  {
    "lap": 1,
    "time": {
      "time": 126792,
      "formattedTime": "2:06.792"
    },
    "splits": [
      35390,
      48782,
      42620
    ],
    "formattedSplits": [
      "0:35.390",
      "0:48.782",
      "0:42.620"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "15:06",
    "position": 1,
    "trackGripStatus": "FLOODED",
    "tyre": {
      "pressure": {
        "frontLeft": 28.47462272644043,
        "frontRight": 28.639198303222656,
        "rearLeft": 28.28776741027832,
        "rearRight": 28.462360382080078
      },
      "temperature": {
        "frontLeft": 28.913715362548828,
        "frontRight": 27.503049850463867,
        "rearLeft": 30.0922794342041,
        "rearRight": 28.785980224609375
      },
      "compound": "WET",
      "currentTyreSet": 0
    },
    "environment": {
      "airTemperature": 14.666903495788574,
      "roadTemperature": 18.479572296142578,
      "rainIntensity": "HEAVY RAIN",
      "windSpeed": 0,
      "windDirection": 0,
      "rainIntensityIn10min": "HEAVY RAIN",
      "rainIntensityIn30min": "HEAVY RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 35.33238220214844,
      "fuelRealUsed": 2.7699999809265137,
      "fuelXLap": 2.7699999809265137,
      "usedFuel": 4.667484283447266,
      "fuelEstimatedLaps": 12.755420684814453,
      "tc": 6,
      "tcCut": 4,
      "abs": 4
    }
  },
  {
    "lap": 2,
    "time": {
      "time": 127980,
      "formattedTime": "2:07.980"
    },
    "splits": [
      36015,
      49447,
      42517
    ],
    "formattedSplits": [
      "0:36.015",
      "0:49.447",
      "0:42.517"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "15:12",
    "position": 1,
    "trackGripStatus": "FLOODED",
    "tyre": {
      "pressure": {
        "frontLeft": 29.15983772277832,
        "frontRight": 29.302400588989258,
        "rearLeft": 28.88279914855957,
        "rearRight": 29.04924964904785
      },
      "temperature": {
        "frontLeft": 30.8564395904541,
        "frontRight": 29.205429077148438,
        "rearLeft": 31.1964168548584,
        "rearRight": 29.693435668945312
      },
      "compound": "WET",
      "currentTyreSet": 0
    },
    "environment": {
      "airTemperature": 14.640822410583496,
      "roadTemperature": 18.41163444519043,
      "rainIntensity": "HEAVY RAIN",
      "windSpeed": 0,
      "windDirection": 0,
      "rainIntensityIn10min": "HEAVY RAIN",
      "rainIntensityIn30min": "HEAVY RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 35.10271453857422,
      "fuelRealUsed": 0.22966766357421875,
      "fuelXLap": 2.4372329711914062,
      "usedFuel": 4.897132873535156,
      "fuelEstimatedLaps": 14.402753829956055,
      "tc": 6,
      "tcCut": 4,
      "abs": 5
    }
  },
  {
    "lap": 3,
    "time": {
      "time": 125312,
      "formattedTime": "2:05.312"
    },
    "splits": [
      35045,
      48450,
      41817
    ],
    "formattedSplits": [
      "0:35.045",
      "0:48.450",
      "0:41.817"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "15:14",
    "position": 1,
    "trackGripStatus": "FLOODED",
    "tyre": {
      "pressure": {
        "frontLeft": 29.2358455657959,
        "frontRight": 29.37594223022461,
        "rearLeft": 28.905345916748047,
        "rearRight": 29.06195068359375
      },
      "temperature": {
        "frontLeft": 31.654319763183594,
        "frontRight": 29.977642059326172,
        "rearLeft": 31.43743896484375,
        "rearRight": 29.831876754760742
      },
      "compound": "WET",
      "currentTyreSet": 0
    },
    "environment": {
      "airTemperature": 14.631610870361328,
      "roadTemperature": 18.387651443481445,
      "rainIntensity": "HEAVY RAIN",
      "windSpeed": 0,
      "windDirection": 0,
      "rainIntensityIn10min": "HEAVY RAIN",
      "rainIntensityIn30min": "HEAVY RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 32.703041076660156,
      "fuelRealUsed": 2.3996734619140625,
      "fuelXLap": 2.4638195037841797,
      "usedFuel": 7.2969207763671875,
      "fuelEstimatedLaps": 13.27332592010498,
      "tc": 6,
      "tcCut": 4,
      "abs": 5
    }
  },
  {
    "lap": 4,
    "time": {
      "time": 125227,
      "formattedTime": "2:05.227"
    },
    "splits": [
      34735,
      48292,
      42200
    ],
    "formattedSplits": [
      "0:34.735",
      "0:48.292",
      "0:42.200"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "15:16",
    "position": 1,
    "trackGripStatus": "FLOODED",
    "tyre": {
      "pressure": {
        "frontLeft": 29.247079849243164,
        "frontRight": 29.413440704345703,
        "rearLeft": 28.914976119995117,
        "rearRight": 29.100610733032227
      },
      "temperature": {
        "frontLeft": 31.777667999267578,
        "frontRight": 30.37453842163086,
        "rearLeft": 31.544048309326172,
        "rearRight": 30.24089813232422
      },
      "compound": "WET",
      "currentTyreSet": 0
    },
    "environment": {
      "airTemperature": 14.622152328491211,
      "roadTemperature": 18.363037109375,
      "rainIntensity": "HEAVY RAIN",
      "windSpeed": 0,
      "windDirection": 0,
      "rainIntensityIn10min": "HEAVY RAIN",
      "rainIntensityIn30min": "HEAVY RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 30.23468780517578,
      "fuelRealUsed": 2.468353271484375,
      "fuelXLap": 2.474940061569214,
      "usedFuel": 9.765237808227539,
      "fuelEstimatedLaps": 12.216361045837402,
      "tc": 6,
      "tcCut": 4,
      "abs": 5
    }
  },
  {
    "lap": 5,
    "time": {
      "time": 124065,
      "formattedTime": "2:04.065"
    },
    "splits": [
      34530,
      47545,
      41990
    ],
    "formattedSplits": [
      "0:34.530",
      "0:47.545",
      "0:41.990"
    ],
    "type": "Regular",
    "valid": true,
    "boxLap": false,
    "clock": "15:18",
    "position": 1,
    "trackGripStatus": "FLOODED",
    "tyre": {
      "pressure": {
        "frontLeft": 29.219541549682617,
        "frontRight": 29.411890029907227,
        "rearLeft": 28.911081314086914,
        "rearRight": 29.119640350341797
      },
      "temperature": {
        "frontLeft": 31.497264862060547,
        "frontRight": 30.364856719970703,
        "rearLeft": 31.50994300842285,
        "rearRight": 30.445573806762695
      },
      "compound": "WET",
      "currentTyreSet": 0
    },
    "environment": {
      "airTemperature": 14.612455368041992,
      "roadTemperature": 18.33780860900879,
      "rainIntensity": "HEAVY RAIN",
      "windSpeed": 0,
      "windDirection": 0,
      "rainIntensityIn10min": "HEAVY RAIN",
      "rainIntensityIn30min": "HEAVY RAIN"
    },
    "carInfo": {
      "damage": {
        "front": 0,
        "rear": 0,
        "left": 0,
        "right": 0,
        "center": 0,
        "totalDamage": 0,
        "isDamaged": false,
        "time": "0m00s"
      },
      "fuel": 27.790681838989258,
      "fuelRealUsed": 2.4440059661865234,
      "fuelXLap": 2.523212432861328,
      "usedFuel": 12.209226608276367,
      "fuelEstimatedLaps": 11.014043807983398,
      "tc": 6,
      "tcCut": 4,
      "abs": 5
    }
  }
]

=== arkroger/acc-training/acc-json-tools/demo_rules_input.json
[
  {
    "lap": 1,
    "type": "Outlap",
    "valid": true,
    "time": {
      "time": 95000
    },
    "splits": [
      31000,
      32000,
      32000
    ],
    "tyre": {
      "currentTyreSet": 3
    },
    "carInfo": {
      "fuel": 60
    }
  },
  {
    "lap": 2,
    "type": "Regular",
    "valid": true,
    "time": {
      "time": 90000
    },
    "splits": [
      30000,
      30000,
      30000
    ],
    "tyre": {
      "currentTyreSet": 3
    },
    "carInfo": {
      "fuel": 57
    }
  },
  {
    "lap": 3,
    "type": "Regular",
    "valid": true,
    "time": {
      "time": 90500
    },
    "splits": [
      30200,
      30000,
      30300
    ],
    "tyre": {
      "currentTyreSet": 4
    },
    "carInfo": {
      "fuel": 54
    }
  },
  {
    "lap": 4,
    "type": "Regular",
    "valid": true,
    "time": {
      "time": 91000
    },
    "splits": [
      30500,
      30000,
      30500
    ],
    "tyre": {
      "currentTyreSet": 4
    },
    "carInfo": {
      "fuel": 51
    }
  },
  {
    "lap": 5,
    "type": "Inlap",
    "valid": true,
    "time": {
      "time": 100000
    },
    "splits": [
      31000,
      31000,
      38000
    ],
    "tyre": {
      "currentTyreSet": 4
    },
    "carInfo": {
      "fuel": 49
    }
  }
]
